#!/usr/bin/python3
import sys
import statistics

def main():
    nums = []
    for line in sys.stdin:
        nums.append(float(line.strip()))

    if nums:
        print(f"合計: {sum(nums)}")
        print(f"平均: {statistics.mean(nums)}")
        print(f"中央値: {statistics.median(nums)}")
        print(f"最大値: {max(nums)}")
        print(f"最小値: {min(nums)}")
        print(f"数: {len(nums)}")

if __name__ == "__main__":
    main()

